Remove blanket pidfile configuration
Configure pidfile only on the OS that need it. Improve testing
resiliency to check for proper unbound configuration.

The role is failing to start unbound on xenial because:
error: cannot open pidfile /var/run/unbound/unbound.pid: No such file or directory

This issue is exposed by unbound-checkconf:
unbound-checkconf[956:0] fatal error: pidfile directory does not exist